/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn pipewire_start(
        node_id: ::std::os::raw::c_uint,
        user_data: *mut ::std::os::raw::c_void,
        on_process: ::std::option::Option<
            unsafe extern "C" fn(user_data: *mut ::std::os::raw::c_void),
        >,
    ) -> ::std::os::raw::c_int;
}
